/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  FixtableOptions,
} from './components/fixtable-grid/fixtable-grid';

declare global {

  namespace StencilComponents {
    interface FixtableDemo {

    }
  }

  interface HTMLFixtableDemoElement extends StencilComponents.FixtableDemo, HTMLStencilElement {}

  var HTMLFixtableDemoElement: {
    prototype: HTMLFixtableDemoElement;
    new (): HTMLFixtableDemoElement;
  };
  interface HTMLElementTagNameMap {
    'fixtable-demo': HTMLFixtableDemoElement;
  }
  interface ElementTagNameMap {
    'fixtable-demo': HTMLFixtableDemoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'fixtable-demo': JSXElements.FixtableDemoAttributes;
    }
  }
  namespace JSXElements {
    export interface FixtableDemoAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface FixtableGrid {
      'columnFilters': any[];
      'data': any[];
      'options': FixtableOptions;
    }
  }

  interface HTMLFixtableGridElement extends StencilComponents.FixtableGrid, HTMLStencilElement {}

  var HTMLFixtableGridElement: {
    prototype: HTMLFixtableGridElement;
    new (): HTMLFixtableGridElement;
  };
  interface HTMLElementTagNameMap {
    'fixtable-grid': HTMLFixtableGridElement;
  }
  interface ElementTagNameMap {
    'fixtable-grid': HTMLFixtableGridElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'fixtable-grid': JSXElements.FixtableGridAttributes;
    }
  }
  namespace JSXElements {
    export interface FixtableGridAttributes extends HTMLAttributes {
      'columnFilters'?: any[];
      'data'?: any[];
      'options'?: FixtableOptions;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;